# yaml-language-server: $schema=../../schemas/v1/job.yaml
using:
  engine: openai
  # engine: ollama
  # model: llama3.3

jobs:
  update-readme:
    steps:
      - uses: chat
        system: |
          You are a technical writer tasked with updating the README.md file for an open source project hosted on GitHub. You are good at writing documentation for software developers, and excel in writing succint but useful documents.
        message: |
          Write the readme file in the GitHub format for axle. axle stands for AI eXecution and Logic Engine.

          axle is a command line tool for running workflows against LLM APIs. Users can create complex multi-step workflows and interact with the file system. As such, the tool is useful for complex interactions and automating repetitive tasks.

          Include the following sections:
            - Introduction
            - Installation
            - Usage
            - Configuration format
            - Job file format

          For the job file format section, please mention the different types of steps that can be taken, and the options for each type of step.

          The source code for the repository is here: ${input}
        replace:
          - source: file
            pattern: ${input}
            files:
              - ./src/**/*.ts
              - ./examples/*.yml
              - ./package.json
      - uses: write-to-disk
        output: ./output/readme.md
