import { AxleStopReason } from "../providers/types.js";
import type { FileInfo } from "../utils/file.js";

/**
 * Model-facing conversation message.
 *
 * This is Axle's canonical conversation state. Providers consume these
 * messages after adapter-specific conversion, while turns are derived from
 * them for presentation.
 */
export type AxleMessage = AxleUserMessage | AxleAssistantMessage | AxleToolCallMessage;

/**
 * Host-owned render metadata attached to a message.
 *
 * Providers ignore this data; it exists so hosts can carry stable presentation
 * hints through history and into renderable turns.
 */
export type MessageMetadata = Record<string, unknown>;

/**
 * Content returned by a tool call.
 *
 * Tool results may be simple text or structured parts when the result includes
 * file data. Deferred file sources remain authored in history and are resolved
 * at each provider conversion boundary so expiring URLs are not persisted.
 */
export type ToolResultPart = { type: "text"; text: string } | { type: "file"; file: FileInfo };

/**
 * Message authored by the user or host application.
 */
export interface AxleUserMessage {
  /** Message role discriminator. */
  role: "user";
  /** Stable message id. Generated by Axle when a user turn is compiled. */
  id?: string;
  /** Optional user name passed through to providers that support it. */
  name?: string;
  /** User-authored text or mixed content parts. */
  content: string | Array<ContentPart>;
  /** Stable host-owned render metadata copied to the corresponding user turn. */
  metadata?: MessageMetadata;
}

/**
 * Message authored by the assistant/model.
 */
export interface AxleAssistantMessage {
  /** Message role discriminator. */
  role: "assistant";
  /** Stable assistant message id. */
  id: string;
  /** Model identifier that produced this message, when known. */
  model?: string;
  /** Assistant content parts in model order. */
  content: Array<
    | ContentPartText
    | ContentPartThinking
    | ContentPartToolCall
    | ContentPartProviderTool
    | ContentPartCitation
  >;
  /** Provider-normalized reason the assistant message stopped. */
  finishReason?: AxleStopReason;
}

/**
 * Message carrying results for one or more tool calls.
 */
export interface AxleToolCallMessage {
  /** Message role discriminator. */
  role: "tool";
  /** Stable tool-result message id. */
  id: string;
  /** Tool call results included in this message. */
  content: Array<AxleToolCallResult>;
}

/**
 * Result payload for a single tool call.
 */
export interface AxleToolCallResult {
  /** Tool call id this result answers. */
  id: string;
  /** Tool name that produced the result. */
  name: string;
  /** Tool result content. */
  content: string | ToolResultPart[];
  /** Whether the tool result represents an execution error. */
  isError?: boolean;
}

/**
 * Any content part Axle can carry in a user or assistant message.
 */
export type ContentPart =
  | ContentPartText
  | ContentPartFile
  | ContentPartToolCall
  | ContentPartThinking
  | ContentPartProviderTool
  | ContentPartCitation;

/**
 * Plain text content.
 */
export interface ContentPartText {
  /** Part discriminator. */
  type: "text";
  /** Text content. */
  text: string;
  /** Source citations that support spans of this text, when supplied by the provider. */
  citations?: Citation[];
  /** Provider-specific metadata that is not part of Axle's normalized contract. */
  providerMetadata?: Record<string, unknown>;
}

/**
 * File attachment content.
 */
export interface ContentPartFile {
  /** Part discriminator. */
  type: "file";
  /** File metadata and source reference. */
  file: FileInfo;
}

/**
 * Model reasoning or thinking content.
 */
export interface ContentPartThinking {
  /** Part discriminator. */
  type: "thinking";
  /** Provider thinking block id, when supplied. */
  id?: string;
  /** Renderable reasoning text content, when the provider exposes it. */
  text?: string;
  /** Optional provider-supplied reasoning summary. */
  summary?: string;
  /** Whether the provider redacted the reasoning content. */
  redacted?: boolean;
  /** Provider continuity payload that should be preserved for future requests. */
  continuity?: ThinkingContinuity;
  /** Provider-specific metadata that is not part of Axle's normalized contract. */
  providerMetadata?: Record<string, unknown>;
}

/**
 * Source attribution attached to model text.
 *
 * Providers expose citations with different source records and locator
 * metadata. Axle keeps the common renderable surface small: what source is
 * cited, and where that citation applies in the generated output text.
 */
export interface Citation {
  /** Source being cited. */
  source: CitationSource;
  /** Character/byte offsets in the generated output text, when supplied. */
  outputSpan?: CitationOutputSpan;
  /** Provider-specific citation payload fields not covered by the normalized shape. */
  providerMetadata?: Record<string, unknown>;
}

/**
 * Citation source categories Axle currently normalizes from provider APIs.
 */
export type CitationSource =
  | {
      type: "web";
      title?: string;
      url: string;
      citedText?: string;
    }
  | {
      type: "document";
      title?: string;
      fileId?: string;
      citedText?: string;
      locator?: DocumentLocator;
    }
  | {
      type: "search-result";
      title?: string;
      url?: string;
      citedText?: string;
      locator?: DocumentLocator;
    }
  | {
      type: "retrieved-context";
      title?: string;
      uri?: string;
      citedText?: string;
      locator?: DocumentLocator;
    }
  | {
      type: "unknown";
      citedText?: string;
    };

/**
 * Provider-reported location inside a cited source.
 */
export type DocumentLocator =
  | { type: "char"; start?: number; end?: number }
  | { type: "page"; start?: number; end?: number }
  | { type: "block"; start?: number; end?: number }
  | { type: "part"; index?: number };

/**
 * Citation coordinates in generated output text.
 */
export interface CitationOutputSpan {
  /** Inclusive output offset. */
  start?: number;
  /** Exclusive output offset. */
  end?: number;
}

/**
 * Opaque provider state needed to continue reasoning across requests.
 */
export type ThinkingContinuity =
  | { provider: "openai"; encrypted: string }
  | { provider: "anthropic"; signature?: string; redactedData?: string }
  | { provider: "gemini"; thoughtSignature: string };

/**
 * Axle-managed tool call request emitted by the assistant.
 */
export interface ContentPartToolCall {
  /** Part discriminator. */
  type: "tool-call";
  /** Tool call id used to pair the call with its result. */
  id: string;
  /** Tool name to execute. */
  name: string;
  /** Parsed tool parameters. */
  parameters: Record<string, unknown>;
  /** Provider-specific metadata associated with the tool call. */
  providerMetadata?: Record<string, unknown>;
}

/**
 * Provider-managed built-in tool call or result.
 */
export interface ContentPartProviderTool {
  /** Part discriminator. */
  type: "provider-tool";
  /** Provider tool call id. */
  id: string;
  /** Provider tool name. */
  name: string;
  /** Provider-specific tool input. */
  input?: unknown;
  /** Provider-specific tool output. */
  output?: unknown;
}

/**
 * Unanchored provider citations or sources associated with the assistant output.
 *
 * Text-span citations remain attached to `ContentPartText.citations`. This part
 * is for source lists that the provider emits as their own ordered stream item.
 */
export interface ContentPartCitation {
  /** Part discriminator. */
  type: "citation";
  /** Source citations carried by this ordered part. */
  citations: Citation[];
  /** Provider-specific metadata that is not part of Axle's normalized contract. */
  providerMetadata?: Record<string, unknown>;
}
