import { AxleStopReason } from "../providers/types.js";
import { ConcreteFileInfo, FileInfo } from "../utils/file.js";

/**
 * Model-facing conversation message.
 *
 * This is Axle's canonical conversation state. Providers consume these
 * messages after adapter-specific conversion, while turns are derived from
 * them for presentation.
 */
export type AxleMessage = AxleUserMessage | AxleAssistantMessage | AxleToolCallMessage;

/**
 * Host-owned render metadata attached to a message.
 *
 * Providers ignore this data; it exists so hosts can carry stable presentation
 * hints through history and into renderable turns.
 */
export type MessageMetadata = Record<string, unknown>;

/**
 * Content returned by a tool call.
 *
 * Tool results may be simple text or structured parts when the result includes
 * file data.
 */
export type ToolResultPart =
  | { type: "text"; text: string }
  | { type: "file"; file: ConcreteFileInfo };

/**
 * Message authored by the user or host application.
 */
export interface AxleUserMessage {
  /** Message role discriminator. */
  role: "user";
  /** Stable message id. Generated by Axle when a user turn is compiled. */
  id?: string;
  /** Optional user name passed through to providers that support it. */
  name?: string;
  /** User-authored text or mixed content parts. */
  content: string | Array<ContentPart>;
  /** Stable host-owned render metadata copied to the corresponding user turn. */
  metadata?: MessageMetadata;
}

/**
 * Message authored by the assistant/model.
 */
export interface AxleAssistantMessage {
  /** Message role discriminator. */
  role: "assistant";
  /** Stable assistant message id. */
  id: string;
  /** Model identifier that produced this message, when known. */
  model?: string;
  /** Assistant content parts in model order. */
  content: Array<
    ContentPartText | ContentPartThinking | ContentPartToolCall | ContentPartProviderTool
  >;
  /** Provider-normalized reason the assistant message stopped. */
  finishReason?: AxleStopReason;
}

/**
 * Message carrying results for one or more tool calls.
 */
export interface AxleToolCallMessage {
  /** Message role discriminator. */
  role: "tool";
  /** Stable tool-result message id. */
  id: string;
  /** Tool call results included in this message. */
  content: Array<AxleToolCallResult>;
}

/**
 * Result payload for a single tool call.
 */
export interface AxleToolCallResult {
  /** Tool call id this result answers. */
  id: string;
  /** Tool name that produced the result. */
  name: string;
  /** Tool result content. */
  content: string | ToolResultPart[];
  /** Whether the tool result represents an execution error. */
  isError?: boolean;
}

/**
 * Any content part Axle can carry in a user or assistant message.
 */
export type ContentPart =
  | ContentPartText
  | ContentPartFile
  | ContentPartToolCall
  | ContentPartThinking
  | ContentPartProviderTool;

/**
 * Plain text content.
 */
export interface ContentPartText {
  /** Part discriminator. */
  type: "text";
  /** Text content. */
  text: string;
}

/**
 * File attachment content.
 */
export interface ContentPartFile {
  /** Part discriminator. */
  type: "file";
  /** File metadata and source reference. */
  file: FileInfo;
}

/**
 * Model reasoning or thinking content.
 */
export interface ContentPartThinking {
  /** Part discriminator. */
  type: "thinking";
  /** Provider thinking block id, when supplied. */
  id?: string;
  /** Reasoning text content. */
  text: string;
  /** Optional provider-supplied reasoning summary. */
  summary?: string;
  /** Whether the provider redacted the reasoning content. */
  redacted?: boolean;
  /** Provider-encrypted reasoning payload, when supplied. */
  encrypted?: string;
  /** Provider verification signature, when supplied. */
  signature?: string;
}

/**
 * Axle-managed tool call request emitted by the assistant.
 */
export interface ContentPartToolCall {
  /** Part discriminator. */
  type: "tool-call";
  /** Tool call id used to pair the call with its result. */
  id: string;
  /** Tool name to execute. */
  name: string;
  /** Parsed tool parameters. */
  parameters: Record<string, unknown>;
  /** Provider-specific metadata associated with the tool call. */
  providerMetadata?: Record<string, unknown>;
}

/**
 * Provider-managed built-in tool call or result.
 */
export interface ContentPartProviderTool {
  /** Part discriminator. */
  type: "provider-tool";
  /** Provider tool call id. */
  id: string;
  /** Provider tool name. */
  name: string;
  /** Provider-specific tool input. */
  input?: unknown;
  /** Provider-specific tool output. */
  output?: unknown;
}
