// Generated by scripts/getModelsDev.ts. Do not edit by hand.
//
// Maps a publisher-qualified model identity (as exported from Models) to the
// slug OpenRouter's API expects, for models whose OpenRouter author/casing
// differs from the publisher's canonical form.
export const OpenRouterModelAliases: Record<string, string> = {
  "minimax/MiniMax-M2.7": "minimax/minimax-m2.7",
  "minimax/MiniMax-M3": "minimax/minimax-m3",
  "zai/glm-5.1": "z-ai/glm-5.1",
  "zai/glm-5.2": "z-ai/glm-5.2",
};
